version: "3.9"

services:
  users:
    image: toys-store/users
    build: ./users
    network_mode: "host"
  items:
    image: toys-store/items
    build: ./items
    network_mode: "host"
  carts:
    image: toys-store/carts
    build: ./carts
    network_mode: "host"