name: Review

on:
  pull_request:

jobs:
  review:
    name: Analyze for review
    runs-on: ubuntu-20.04
    env:
      TERM: dumb
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud scan fixed
        uses: pervasive-cats/sonarcloud-scoverage-fix@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
